spring:
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
#  cloud:
#    gateway:
#      routes:
#        - id: Customer
#          uri: http://Customer
#          predicates:
#            - Path=/customers/*
#            -
#        - id: Account
#          uri: http://Account
#          predicates:
#            - Path=/accounts/*, /transactions/*
server:
  port: 8080

