server:
  port: 9990
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: zahra
    password: 1234
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
  application:
    name: customer-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true